version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/data:/data
    command: redis-server --appendonly yes
    networks:
      - webnet   

  redisproxy:
    build:
      context: .
    ports:
      - "10000:10000"
    networks:
      - webnet
      
networks:
  webnet:
